### PR TITLE
Fixes for *ArrayCoefficient classes

### LINKED ISSUE #243: VectorArrayCoefficient and MatrixArrayCoefficient
These classes take ownership of the Coefficient used to evaluate the i-th direction or the (i,j) matrix entry.
Suppose you want to use zero for some direction or matrix entry. As it is right now, you are forced to create fake constant coefficients as CostantCoefficient(0.). I would rather prefer to have the eval methods testing for NULL and set the corresponding entry in the Vector or the DenseMatrix to zero.
This can be handle with quite easily, except for the Coefficient& GetCoefficient()  method that returns a reference instead of a pointer. Is there any specific/historical reason why one wants a reference instead of a pointer?

A note aside: since we assume that these classes take ownership of the single Coefficients used, it should be reasonable to add a call to delete the previous Coefficient used in the SetCoeff calls (which are public). Thoughts? If we agree on the modifications, I would be happy to provide a PR.

### PR DESCRIPTION
**Pull request by stefanozampini**
## Overview
- These classes take ownership of the Coefficients used for the i-th direction or (i,j) entry.
- When a new one is set, the old one should be deleted
- Added capability of handling NULL coefficients, instead of forcing the user to create a zero coefficient.
- Changed signature of GetCoeff, which now returns a pointer (that can be NULL) instead of a reference

Resolves #243.

## TODO
- [x] Update `CHANGELOG`

### CODE REVIEW

File: fem/coefficient.hpp [hunk 1]
```diff
@@ -308,16 +308,16 @@ class VectorArrayCoefficient : public VectorCoefficient
    explicit VectorArrayCoefficient(int dim);
 
    /// Returns i'th coefficient.
-   Coefficient &GetCoeff(int i) { return *Coeff[i]; }
+   Coefficient* GetCoeff(int i) { return Coeff[i]; }
```
Comment (v-dobrev) [inline fem/coefficient.hpp]: I'd like to keep the interface unchanged - it is easier for existing users to upgrade.

File: fem/coefficient.hpp [hunk 2]
```diff
@@ -454,12 +454,12 @@ class MatrixArrayCoefficient : public MatrixCoefficient
 
    explicit MatrixArrayCoefficient (int dim);
 
-   Coefficient &GetCoeff (int i, int j) { return *Coeff[i*vdim+j]; }
+   Coefficient* GetCoeff (int i, int j) { return Coeff[i*vdim+j]; }
```
Comment (v-dobrev) [inline fem/coefficient.hpp]: Once again, I'd like to keep the interface unchanged.

File: fem/coefficient.hpp (hunk 1 above)
Comment (tzanio) [reply fem/coefficient.hpp]: I tend to agree...  maybe we can have another method, `GetCoeffPtr` that returns a pointer? The rest of the PR looks good to me.

Comment (stefanozampini) [reply fem/coefficient.hpp]: I understand you want to keep the current interface, but I still think that returning a reference is non-sense in this case; also, since the functionality in this PR allows for null entries in the coefficient arrays, returning a reference of any of these allowed nulls isn't undefined behaviour?
For users to upgrade, a compilation error with the new interface is better than undefined behaviour at runtime.

Can you give me an example where the return by reference case can be useful?

Comment (tzanio) [reply fem/coefficient.hpp]: I searched for usages of `GetCoeff` and couldn't find any in our codes, so I'm actually OK to break compatibility in this particular case.

Comment (v-dobrev) [reply fem/coefficient.hpp]: I agree that returning a pointer is better choice with the special treatment of the `NULL` case, if there was no method with the same name already. However, in the current situation I'd prefer if we call the new method something else. I think we can add `deprecated` (in the doxygen comment) to the old method and point to the new one.

That said, the above would be my preferred solution but it is not a "line in the sand". :-)

@tzanio, what do you think?

Comment (tzanio) [reply fem/coefficient.hpp]: We all agree that the pointer versions are the better technical decision, so I vote to that and documenting the API change in the `CHANGELOG` file as we've done in the past: https://github.com/mfem/mfem/blob/master/CHANGELOG#L353.

Comment (v-dobrev) [reply fem/coefficient.hpp]: OK. Let's do that.
