### PR TITLE
Final changes for mfem-4.4

### LINKED ISSUE #2890: Issue with MixedVectorIntegrator after recent merge of #1989
I am assembling a MixedBilinearForm which has only boundary integrators on a 3D mesh. After merging #1989, this no longer works and I get the following incompatible dimensions error and backtrace:

```
Assertion failed: (a.Height() == b.Height() && a.Width() == c.Width() && b.Width() == c.Height()) is false:
 --> incompatible dimensions
 ... in function: void mfem::Mult(const mfem::DenseMatrix&, const mfem::DenseMatrix&, mfem::DenseMatrix&)
 ... in file: /Users/sjg/Documents/Repositories/qht-cem/build/extern/mfem/src/mfem/linalg/densemat.cpp:1984

Backtrace:
0) [0x10dc84a1e]: mfem::mfem_error(char const*)
1) [0x10dcc4993]: mfem::Mult(mfem::DenseMatrix const&, mfem::DenseMatrix const&, mfem::DenseMatrix&)
2) [0x10e082c83]: mfem::FiniteElement::CalcPhysDShape(mfem::ElementTransformation&, mfem::DenseMatrix&) const
3) [0x10dbbf48f]: mfem::MixedVectorWeakDivergenceIntegrator::CalcTestShape(mfem::FiniteElement const&, mfem::ElementTransformation&, mfem::DenseMatrix&)
4) [0x10ded92a2]: mfem::MixedVectorIntegrator::AssembleElementMatrix2(mfem::FiniteElement const&, mfem::FiniteElement const&, mfem::ElementTransformation&, mfem::DenseMatrix&)
5) [0x10debb0fa]: mfem::MixedBilinearForm::Assemble(int)
```

It seems the issue is inside `CalcPhysDShape`, the inverse Jacobian is 2 x 3 but the `dshape` matrix (`trial_shape` in `MixedVectorIntegrator::AssembleElementMatrix2`) is now only allocated with 2 columns (`trial_vdim = 2`), whereas it used to always have `spaceDim` columns. The `test_shape` matrix is still constructed with `test_vdim = 3`. I'm not using any of the new ND or RT collections, in this case the test space is a 3D ND space and the trial space is a 3D H1 space.

### PR DESCRIPTION
**Pull request by tzanio**
**Tasks:**
- [x] Merge #2833
- [x] Merge #2739
- [x] Merge #2731
- [x] Merge #2737
- [x] Merge #2741
- [x] Merge #2733
- [x] Merge #2738
- [x] Merge #2840
- [x] Merge #2855
- [x] Merge #2860
- [x] Merge #2856
- [x] Merge #2861
- [x] Merge #2864
- [x] Merge #1989
- [x] Merge #2880
- [x] Merge #2881
- [x] Merge #2875
- [x] Merge #2844
- [x] Merge #2886
- [x] Merge #2885
- [x] Merge #2825 
- [x] [Address LGTM warnings](https://lgtm.com/projects/g/mfem/mfem?mode=tree&severity=warning)
- [x] Fix #2890
- [x] Merge #2873
- [x] Merge #2883
- [x] Merge #2895 
- [x] Merge #2648
- [x] Merge #2569
- [x] Merge #2898 (into this branch)
- [x] Merge #2903 (into this branch)
- [x] Merge #2904 (into this branch)

**Postponed:**
- Merge #1978
- Merge #2568 
- Merge #2849

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2839](https://github.com/mfem/mfem/pull/2839) | @tzanio | @tzanio | @mlstowell + @YohannDudouit + @camierjs + @pazner + @v-dobrev | 3/8/22 | 3/16/22 | 3/21/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by pazner** [comment]
@v-dobrev, given this commit 7e9b167dd72ca8248a14184c220d105723c0c3f7, should this be changed to `Qk`? https://github.com/mfem/mfem/blob/def8aee025bf65f55c9edc305ec7aebfa9ca743b/tests/unit/fem/test_fe.cpp#L720

**Comment by v-dobrev** [comment]
> @v-dobrev, given this commit [7e9b167](https://github.com/mfem/mfem/commit/7e9b167dd72ca8248a14184c220d105723c0c3f7), should this be changed to `Qk`?
> 
> https://github.com/mfem/mfem/blob/def8aee025bf65f55c9edc305ec7aebfa9ca743b/tests/unit/fem/test_fe.cpp#L720

I did not expect that the `FunctionSpace`s are tested, I'll fix the failing tests.

File: fem/ceed/coefficient.hpp [hunk 1]
```diff
@@ -82,20 +82,20 @@ void InitCoefficient(mfem::Coefficient *Q, mfem::Mesh &mesh,
                      const mfem::IntegrationRule &ir,
                      Coefficient*& coeff_ptr, Context &ctx)
 {
+   ConstantCoefficient *coeff;
```
Comment (pazner) [inline fem/ceed/coefficient.hpp:85]: This is later assigned to `GridFunctionCoefficient*`, it's probably better to keep the declarations inside the `if` statement, and just give them unique names, `const_coeff`, `gf_coeff`, etc.

Comment (tzanio) [reply fem/ceed/coefficient.hpp:85]: yes, yes

I somehow missed the difference

Comment (tzanio) [reply fem/ceed/coefficient.hpp]: Hopefully https://github.com/mfem/mfem/pull/2839/commits/247de1cf04ed70bbe4183e7a898fd74d9b14d4fb is OK

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
@artv3, @tomstitt, @jamiebramwell, @sshiraiwa, @tepperly, @koning and everyone else interested 😄 

This branch is now a release candidate for `mfem-4.4` which will be tagged tomorrow, March 18th, or early next week at the latest.

Can you please test it in your applications and let us know if you see any issues?

Thanks for your help!

Tzanio

File: linalg/dtensor.hpp [hunk 2]
```diff
@@ -111,6 +111,9 @@ class DeviceTensor
       data = t.data;
    }
 
+   /// Copy assignment not supported
+   MFEM_HOST_DEVICE DeviceTensor& operator=(DeviceTensor&) = delete;
```
Comment (artv3) [inline linalg/dtensor.hpp:115]: I ran into a problem when this got deleted. I get the following error from our RAJA/CAMP kernels: 

```
camp-3fb4621/include/camp/tuple.hpp:205:99: error: the parameter for this explicitly-defaulted copy assignment operator is const, but a member or base requires it to be non-const
renamed_intern_namespace::template tuple_helper< camp::idx_seq< Indices...> , list< Types...> >  &operator=(const renamed_intern_namespace::template tuple_helper< camp::idx_seq< Indices...> , list< Types...> >  & rhs) = default;
```

If I remove line 115 my code builds just fine. I'm not sure what would be appropriate here. ping @trws , @v-dobrev

**Review by artv3 — CHANGES_REQUESTED** [review]

File: linalg/dtensor.hpp (hunk 2 above)
Comment (v-dobrev) [reply linalg/dtensor.hpp:115]: For this class we can actually just ` = default` both the copy constructor and the copy assignment. Currently, the copy constructor does what the `= default` version will do.

Comment (tzanio) [reply linalg/dtensor.hpp:115]: Can you make this change in this branch @v-dobrev ?

Comment (v-dobrev) [reply linalg/dtensor.hpp:115]: The error message is actually about the input parameter (r.h.s.) not being `const` -- we should fix that too.

Comment (trws) [reply linalg/dtensor.hpp:115]: First try changing line 115 to accept a `const DeviceTensor&` and see if it makes a difference.  The signature of a copy assignment deletion should always have the const in it, I'm not sure what this version will do.

Aside from that, if copy assignment isn't supported, and someone tries to copy assign a tuple containing one of these, it is supposed to error out.  We'd need to figure out what contracts to enforce here to figure out how exactly to fix it if it isn't just a type mismatch mistake.

Comment (v-dobrev) [reply linalg/dtensor.hpp]: Updated.

Comment (artv3) [reply linalg/dtensor.hpp]: Using `   MFEM_HOST_DEVICE DeviceTensor& operator=(const DeviceTensor& ) = default;` worked for me. I can try switching default to be delete and trying that as well.

Comment (v-dobrev) [reply linalg/dtensor.hpp]: It looks like `nvcc` issues warnings with `__host__ __device__` and `= default` -- I'll try removing `__host__ __device__` to see that works without warnings.

Comment (trws) [reply linalg/dtensor.hpp]: It should stop the warnings, but we've seen a few times that it will spuriously frail to generate the default the right way.  If that happens, it may have to be explicit for a while until updating to a sufficiently new nvcc.

Comment (v-dobrev) [reply linalg/dtensor.hpp]: Seems to be okay with CUDA 10.1.243. I'll just drop the `MFEM_HOST_DEVICE`. Hopefully HIP will be okay with that too.

Comment (v-dobrev) [reply linalg/dtensor.hpp]: Pushed.

Comment (artv3) [reply linalg/dtensor.hpp]: #TeamWork!

File: linalg/hypre.cpp [hunk 3]
```diff
@@ -33,7 +33,7 @@ namespace mfem
 
 Hypre::Hypre()
 {
-#if MFEM_HYPRE_VERSION >= 21500
+#if MFEM_HYPRE_VERSION >= 21900
```
Comment (v-dobrev) [inline linalg/hypre.cpp:36]: `HYPRE_Init` is available in hypre v2.15.0, it just has arguments: https://github.com/hypre-space/hypre/blob/v2.15.0/src/utilities/_hypre_utilities.h#L1767 -- we can just use `(0, NULL)` for versions >= 2.15.0 and < 2.19.0.

Comment (tzanio) [reply linalg/hypre.cpp:36]: We can, but I think it is also fine not to leave it as is. We did not support `HYPRE_Init` until recently, so it is fine if we don't support it for versions  >= 2.15.0 and < 2.19.0

Comment (v-dobrev) [reply linalg/hypre.cpp:36]: Then this version check should be used also for `HYPRE_Finalize()`: https://github.com/mfem/mfem/blob/c7c4e7ce3a585f1b1b7ffe71d31452658fc728ad/linalg/hypre.cpp#L50-L52.

Comment (tzanio) [reply linalg/hypre.cpp:36]: Done

**Review by rcarson3 — APPROVED** [review]

**Review by sshiraiwa — APPROVED** [review]
I think it is good to go from Wrapper point of view

**Review by jamiebramwell — APPROVED** [review]

**Review by tomstitt — APPROVED** [review]

**Review by artv3 — APPROVED** [review]

**Comment by sshiraiwa** [comment]
Very minor thing I noticed...

This line below says "parallel bilinearform", but since it is serial example, it is probably not right.
https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L133

Sample run suggest to use hexagon.mesh, but it does not exist in data folder, isn't it?
https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L6

**Comment by tzanio** [comment]
> This line below says "parallel bilinearform", but since it is serial example, it is probably not right. https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L133

Good point, I'll fix it

> Sample run suggest to use hexagon.mesh, but it does not exist in data folder, isn't it? https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L6

Hmm, `data/hexagon.mesh` should be there: https://github.com/mfem/mfem/blob/master/data/hexagon.mesh. (It was added recently in https://github.com/mfem/mfem/pull/1989)

**Comment by sshiraiwa** [comment]
> > This line below says "parallel bilinearform", but since it is serial example, it is probably not right. https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L133
> 
> Good point, I'll fix it
> 
> > Sample run suggest to use hexagon.mesh, but it does not exist in data folder, isn't it? https://github.com/mfem/mfem/blob/mfem-4.4-dev/examples/ex31.cpp#L6
> 
> Hmm, `data/hexagon.mesh` should be there: https://github.com/mfem/mfem/blob/master/data/hexagon.mesh. (It was added recently in #1989)

My bad. Thanks!

**Review by YohannDudouit — APPROVED** [review]

**Review by camierjs — APPROVED** [review]
