### PR TITLE
Fix reading VTK surface meshes [vtk-surface-fix]

### LINKED ISSUE #2547: Finite element calculation of 3D surface
Dear MFEM Maintainer 

  I have a finite element model of 3D curved surface, and I wonder if MFEM can solve it.

  I input the mesh model into the EX2 of MFEM and try to solve it, but it seems that the EX2 of MEFM only solves the problems of 2D  plane model and 3D solid model.I input my model into the EX2 solution, but the node displacement is only in the X and Y directions, which is obviously not what I want.

For this 3D surface model, if it is in ANSYS, a thickness parameter needs to be specified, I would like to ask if MFEM can do the same.

If possible, please let me know what I need to know, I would be very grateful!

### PR DESCRIPTION
**Pull request by pazner**
The mesh space dimension was not set correctly in the VTK mesh reader when reading straight sided surface meshes.

Resolves #2547 and #2563.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2566](https://github.com/mfem/mfem/pull/2566) | @pazner | @tzanio | @tzanio + @bslazarov + @mlstowell | 09/23/21 | 09/26/21 | 09/27/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
@HFH104864 can you confirm this works for you?

(I can add you as a reviewer, if you accept the invite to join the MFEM organization)

**Review by tzanio — APPROVED** [review]
Thanks @pazner !

**Comment by ChaoW95** [comment]
This pull request works for my .vtu 3D surface mesh model.

**Comment by pazner** [comment]
> This pull request works for my .vtu 3D surface mesh model.

Great, thanks for checking!

**Review by ChaoW95 — APPROVED** [review]
This pull request works for my .vtu 3D surface mesh model.

File: mesh/mesh_readers.cpp [hunk 1]
```diff
@@ -426,6 +426,28 @@ void Mesh::CreateVTKMesh(const Vector &points, const Array<int> &cell_data,
...
+   {
+      double min_value, max_value;
+      for (int d = 3; d > 0; --d)
+      {
+         min_value = max_value = points(3*0 + d-1);
+         for (int i = 1; i < np; i++)
+         {
+            min_value = std::min(min_value, points(3*i + d-1));
+            max_value = std::max(max_value, points(3*i + d-1));
+            if (min_value != max_value)
```
Comment (mlstowell) [inline mesh/mesh_readers.cpp:441]: Is it appropriate to ignore the possibility of roundoff error here?

Comment (pazner) [reply mesh/mesh_readers.cpp:441]: Yes, I think so. If the mesh is 2D, then all z-coordinates are set to some fixed value (usually 0). I don't know under what circumstances the user would perform arithmetic operations on the z-coordinate leading to round-off errors when the mesh is 2D.

Comment (mlstowell) [reply mesh/mesh_readers.cpp:441]: I was thinking of the mesh generator itself. I don't like to trust black boxes...

But you're probably right.

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...
