### PR TITLE
Fix GLVis issue with subnormals Apple Clang

### LINKED ISSUE #1843: Error when visualizing with GLVis the solutions of ex15
Dear all, 

There seems to be an issue when trying to visualize consecutive solutions in GLVis produced by `ex15/ex15p`. 
A minimal example run that causes the problem is `./ex15`, and it appears at `Time = 0.23` with 
`Error in send(): Broken pipe`

The error appears in both serial and parallel builds of mfem (`master` branch) in debug mode. This also happens with both glvis-3.4 and the latest `modern-ogl-dev` branch of GLVis. 

My compiler/OS configuration is `Apple clang version 12.0.0 (clang-1200.0.32.21)` on `MacOS Catalina Version 10.15.7(19H2)`.

Thanks, 

Socratis

### PR DESCRIPTION
**Pull request by pazner**
Fixes #1843.

Zero out subnormal numbers when writing a Vector to an output stream. When reading a Vector from an input stream with Apple Clang, ignore "out of range" errors, which can be caused by (correctly) parsing subnormal numbers.

### CODE REVIEW

**Review by tzanio — APPROVED** [review]
This looks good and fixes the issue for me, thanks @pazner!

My only concern is about `fpclassify` -- does anyone know how portable that is?

**Comment by tzanio** [comment]
LGTM

**Comment by pazner** [comment]
> My only concern is about `fpclassify` -- does anyone know how portable that is?

`fpclassify` is part of the C++11 standard, so in principle it should be portable. I don't know if there are exceptions to this in practice.

**Comment by termi-official** [comment]
Hi @pazner, amazing track down of this issue!

I just want to share, that I can reproduce the bug (https://github.com/mfem/mfem/issues/1843#issuecomment-717481094) with clang 8 and libc++ on linux based systems. So this most likely a bug in libc++.

File: linalg/vector.cpp [hunk 1]
```diff
@@ -68,6 +68,12 @@ void Vector::Load(std::istream **in, int np, int *dim)
       for (j = 0; j < dim[i]; j++)
       {
          *in[i] >> data[p++];
+#if defined __APPLE__ && defined __clang__
```
Comment (pazner) [inline linalg/vector.cpp:71]: Perhaps we should change this to something like `#ifdef _LIBCPP_VERSION` to detect libc++, which appears to be the source of the issue.

**Comment by pazner** [comment]
> I just want to share, that I can reproduce the bug ([#1843 (comment)](https://github.com/mfem/mfem/issues/1843#issuecomment-717481094)) with clang 8 and libc++ on linux based systems. So this most likely a bug in libc++.

This is a good piece of information to have, thanks!

**Comment by termi-official** [comment]
> > I just want to share, that I can reproduce the bug ([#1843 (comment)](https://github.com/mfem/mfem/issues/1843#issuecomment-717481094)) with clang 8 and libc++ on linux based systems. So this most likely a bug in libc++.
> 
> This is a good piece of information to have, thanks!

Digging a bit further this behavior is not a bug in libc++, but rather *implementation-defined* behavior. This boils down to the fact that the parsing of floating points is defined to be dependent on the behavior *strtoX* of the c library (http://eel.is/c++draft/facet.num.get.virtuals#3.3.3 and following), but strtoX is implementation-defined (see http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf §7.22.1.3 on page 344).

For more details and acknowledgements see this post https://stackoverflow.com/questions/48086830/stdstod-throws-out-of-range-error-for-a-string-that-should-be-valid/48087390#48087390

File: linalg/vector.cpp (hunk 1 above)
Comment (termi-official) [reply linalg/vector.cpp:71]: Why would we need this macro in the first place? If we do not want this code in release builds for performance reasons, then a debug build check should be enough. However I would not expect this additional branch to affect the performance anyway.

**Comment by pazner** [comment]
> Digging a bit further this behavior is not a bug in libc++, but rather _implementation-defined_ behavior. This boils down to the fact that the parsing of floating points is defined to be dependent on the behavior _strtoX_ of the c library (http://eel.is/c++draft/facet.num.get.virtuals#3.3.3 and following), but strtoX is implementation-defined (see http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf §7.22.1.3 on page 344).
> 
> For more details and acknowledgements see this post https://stackoverflow.com/questions/48086830/stdstod-throws-out-of-range-error-for-a-string-that-should-be-valid/48087390#48087390

Yes, it does appear that the standard allows this behavior. However, it also seems undesirable that `ostream` writes values that `istream` doesn't read without errors. An LLVM bug was filed about this (https://bugs.llvm.org/show_bug.cgi?id=39012), but it looks like they couldn't reproduce it for some reason.

File: linalg/vector.cpp (hunk 1 above)
Comment (pazner) [reply linalg/vector.cpp:71]: I would be fine disabling this `#if` check altogether. I'd prefer not to make it debug only.

Comment (v-dobrev) [reply linalg/vector.cpp:71]: I don't think one check (in the normal case) is going to have any measurable performance effect. I think we can always do the check (i.e. remove the `#if ... #endif`) just to be safe. I'm not sure what the effect will be on `Inf`s or `Nan`s which are not read correctly in any case, I think.

Another point: zeroing out denormals during output may not be sufficient by itself -- due to round-off during conversion to text some small normal numbers may become denormals when read back. So I think we can remove the zeroing of denormals when writing to a stream.

Comment (pazner) [reply linalg/vector.cpp]: I removed the `#if`, I agree that this solution makes the most sense.

I think zeroing out the subnormals during output is still useful (even if there are some corner cases where it may not be sufficient). I added this also to the ParaView output, because ParaView has the same issue when reading ASCII files.

**Review by v-dobrev — APPROVED** [review]

File: linalg/vector.cpp (hunk 1 above)
Comment (v-dobrev) [reply linalg/vector.cpp]: I guess it make sense to zero out denormals for paraview at least.
