### PR TITLE
Make ND_SegmentElement inherit from VectorTensorFiniteElement [nd-segment-tensor]

### LINKED ISSUE #2239: Question about mfem::ParFiniteElementSpace::GetFaceRestriction()
I'm trying to use `mfem` to perform integration over a mesh boundary. I'm using `mfem::ParFiniteElementSpace::GetFaceRestriction(mfem::ElementDofOrdering::LEXICOGRAPHIC, mfem::FaceType::Boundary)` to get an operator that sets up the boundary dofs for an elementwise calculation. For the case of a Nedelec ParFiniteElementSpace defined on a mesh of quadrilateral elements, mfem emits the following error message when calling `GetFaceRestriction`:

"Finite element not suitable for lexicographic ordering"

After checking the source, it appears to check if the face element type is a "TensorBasisElement", and if not, it emits this error.

I understand that simplex elements, pyramids, etc. might be more difficult to order lexicographically, but it doesn't seem like there should be a problem for a 1D element. `mfem::H1_SegmentElement` and `mfem::L2_SegmentElement` are `TensorBasisElement`s, but not `ND_SegmentElement`. Is this exception intentional, or is it safe to expand the definition of "lexicographical-suitability" to include all the segment-type elements?

### PR DESCRIPTION
**Pull request by pazner**
Resolves #2239.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2372](https://github.com/mfem/mfem/pull/2372) | @pazner | @tzanio | @dylan-copeland + @mlstowell | 06/30/21 | 07/01/21 | 07/04/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

File: fem/fe.cpp [hunk 1]
```diff
@@ -7950,6 +7950,22 @@ VectorTensorFiniteElement::VectorTensorFiniteElement(const int dims,
...
+                                                     const int d,
+                                                     const int p,
+                                                     const int obtype,
+                                                     const int M,
+                                                     const DofMapType dmtype)
+   : VectorFiniteElement(dims, GetTensorProductGeometry(dims), d,
+                         p, M, FunctionSpace::Pk),
+     TensorBasisElement(dims, p, obtype, dmtype),
+     cbasis1d(poly1d.GetBasis(p, VerifyOpen(obtype))),
+     obasis1d(poly1d.GetBasis(p, VerifyOpen(obtype)))
```
Comment (dylan-copeland) [inline fem/fe.cpp:7963]: There are now 2 constructors for `VectorTensorFiniteElement`, and their behavior is different (e.g. `p` here, `p-1` in the other). Does this mean the other constructor should be not allowed in the 1D case?

**Review by dylan-copeland — APPROVED** [review]

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...
