### PR TITLE
Fix SuperLU interfacing bug with recent hypre version [fix-superlu-hypre2160]

### LINKED ISSUE #983: SuperLU interface is failing with hypre version 2.16.0
Running
```
ex11p -slu
```
crashes with a segfault. This is related to the conversion from a `HypreParMatrix` to `SuperLURowLocMatrix`. I have not investigated further. This is using hypre 2.16.0 and SuperLU_Dist 6.1.1.

I confirmed that hypre 2.10.1 with SuperLU_Dist 6.1.1 works. Also confirmed that hypre 2.15.0 works.

Starting to track it down to
https://github.com/mfem/mfem/blob/878a82cf007b39d62166d73928e060c19fb95d46/linalg/superlu.cpp#L131

`hypre_MergeDiagAndOffd` seems to not return the same thing (comparing 2.15.0 and 2.16.0). Somehow when using 2.16.0 the `colind` pointer is null and therefore the segfault in SuperLU.

### PR DESCRIPTION
**Pull request by jandrej**
This fixes a bug where the column indices are not created with the recent hypre release 2.16.0. Please check if the version checking here is correct.

Resolves #983

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/988 | @jandrej | @tzanio | @tzanio + @mlstowell | 11/23/19 | 12/5/19 | ⌛due 12/12/19 |

### CODE REVIEW

File: linalg/superlu.cpp [hunk 1]
```diff
@@ -130,6 +130,9 @@ SuperLURowLocMatrix::SuperLURowLocMatrix( const HypreParMatrix & hypParMat )
    // hypre_CSRMatrix.
    hypre_CSRMatrix * csr_op = hypre_MergeDiagAndOffd(parcsr_op);
    hypre_CSRMatrixSetDataOwner(csr_op,0);
+#if MFEM_HYPRE_VERSION >= 21600
+   hypre_CSRMatrixBigJtoJ(csr_op);
```
Comment (mlstowell) [inline linalg/superlu.cpp]: Is there a way to check if this is going to succeed?  I suppose we already make the assumption in various places that big ints are not necessary.  If so, I wonder how long that assumption will remain valid...

**Comment by mlstowell** [comment]
Have you looked at recent versions of SuperLU_dist to see if their CSR matrix format supports big ints?  I'm just trying to gauge when we might need to support this as well.

File: linalg/superlu.cpp (hunk 1 above)
Comment (jandrej) [reply linalg/superlu.cpp]: In terms of sustainability?

**Comment by jandrej** [comment]
> Have you looked at recent versions of SuperLU_dist to see if their CSR matrix format supports big ints? I'm just trying to gauge when we might need to support this as well.

They support int64 in their interfaces as a compile option.

It is more a problem due to hypre. Some internal behavior was changed that we rely on in a few different places in the code.

File: linalg/superlu.cpp (hunk 1 above)
Comment (mlstowell) [reply linalg/superlu.cpp]: I was wondering if HYPRE provided another function that could be called before `hyper_CSRMatrixBigJtoJ` to verify that this function would produce usable results.  All this function does is allocate an integer array and copy data from `big_j` to the new array.  If `big_j` contains very large values this copy will produce invalid integers.  Some sort of error checking should also be done.

Comment (mlstowell) [reply linalg/superlu.cpp]: How about this: we first verify that the number of local columns is small enough to be stored as an `int`.  If not then `big_j` most likely contains column indices that are too large to be stored as `ints` and we issue an error because `hyper_CSRMatrixBigJtoJ` will most likely fail.

Comment (jandrej) [reply linalg/superlu.cpp]: I like that approach.

Comment (mlstowell) [reply linalg/superlu.cpp]: Hi, @jandrej, I just put in such a check but I don't have a copy of the appropriate version of HYPRE built to test it.  Would you mind testing this change when you get a chance?

Comment (jandrej) [reply linalg/superlu.cpp]: Seems to work for me.
