### PR TITLE
TMOP corrections

### LINKED ISSUE #414: Mesh Optimizer crash
The following crashes Mesh Optimizer:
```
> mesh-optimizer -o 3 -rs 0 -ji 0.1 -m ../../data/inline-quad.mesh -bnd
```
see https://github.com/mfem/mfem/pull/404#issuecomment-358734576.

Should we exit with more informative message and/or document the assumptions on the boundary attributes, maybe in https://github.com/mfem/mfem/tree/tmop-fix?

### PR DESCRIPTION
**Pull request by vladotomov**
Small corrections in the mesh optimization miniapp.

Resolves #414.

### CODE REVIEW

File: miniapps/meshing/mesh-optimizer.cpp [hunk 1]
```diff
@@ -32,8 +32,22 @@
...
+//   ICF shape and initial size:
+//     ./mesh-optimizer -o 3 -rs 0 -mid 9 -tid 3 -ni 100 -ls 2 -li 100 -bnd -qt 1 -qo 8
+//   ICF shape:
+//     ./mesh-optimizer -o 3 -rs 0 -mid 1 -tid 1 -ni 100 -ls 2 -li 100 -bnd -qt 1 -qo 8
+//   ICF limited shape:
+//     ./mesh-optimizer -o 3 -rs 0 -mid 1 -tid 1 -ni 100 -ls 2 -li 100 -bnd -qt 1 -qo 8 -lc 10
+//   ICF combo shape + size (rings, slow convergence):
+//     ./mesh-optimizer -o 3 -rs 0 -mid 1 -tid 1 -ni 1000 -ls 2 -li 100 -bnd -qt 1 -qo 8 -cmb
+//   3D pinched sphere shape (the mesh is in the mfem/data GitHub repository):
+//   * ./mesh-optimizer -m ../../../mfem_data/ball-pert.mesh -o 4 -rs 0 -mid 303 -tid 1 -ni 20 -ls 2 -li 500 -fix-bnd
```
Comment (tzanio) [inline miniapps/meshing/mesh-optimizer.cpp]: Why the `*`?

Comment (v-dobrev) [reply miniapps/meshing/mesh-optimizer.cpp]: To disable this run for `sample-runs.sh`, since the mesh file is in a separate repo.

File: miniapps/meshing/mesh-optimizer.cpp [hunk 2]
```diff
@@ -519,6 +534,10 @@ int main (int argc, char *argv[])
       for (int i = 0; i < mesh->GetNBE(); i++)
       {
          const int attr = mesh->GetBdrElement(i)->GetAttribute();
+         MFEM_VERIFY(!(dim == 2 && attr == 3),
+                     "Boundary attribute 3 must be used only for 3D meshes. "
+                     "Adjust the attributes (1/2/3 for fixed x/y/z components, "
+                     "4 for free nodes), or use the option -fix-bnd.");
```
Comment (v-dobrev) [inline miniapps/meshing/mesh-optimizer.cpp]: Actually, boundary attribute 4 fixes all components; boundary attribute 5 or larger will leave the nodes free.

File: miniapps/meshing/pmesh-optimizer.cpp [hunk 3]
```diff
@@ -598,6 +601,10 @@ int main (int argc, char *argv[])
       for (int i = 0; i < pmesh->GetNBE(); i++)
       {
          const int attr = pmesh->GetBdrElement(i)->GetAttribute();
+         MFEM_VERIFY(!(dim == 2 && attr == 3),
+                     "Boundary attribute 3 must be used only for 3D meshes. "
+                     "Adjust the attributes (1/2/3 for fixed x/y/z components, "
+                     "4 for free nodes), or use the option -fix-bnd.");
```
Comment (v-dobrev) [inline miniapps/meshing/pmesh-optimizer.cpp]: Same as in the serial version.

File: miniapps/meshing/mesh-optimizer.cpp (hunk 2 above)
Comment (tzanio) [reply miniapps/meshing/mesh-optimizer.cpp]: Fixed

File: miniapps/meshing/mesh-optimizer.cpp (hunk 1 above)
Comment (v-dobrev) [reply miniapps/meshing/mesh-optimizer.cpp]: Actually, the `./` in front of the executable name is also blocking the sample runs from being extracted by `sample-runs.sh`.

Comment (tzanio) [reply miniapps/meshing/mesh-optimizer.cpp]: I think we should remove the `./`
