### PR TITLE
Make sure to call SetPointIndices when constructing IntegrationRules [int-rule-set-point-idx]

### LINKED ISSUE #2333: Setting of IntegrationPoint index variable for Segment IntegrationRule
I believe the method `IntegrationRules::SegmentIntegrationRule` in `intrules.cpp` does not set the `index` member of the `IntegrationPoint` objects created that define the `IntegrationRule` object. This can lead to segfaults when using `QuadratureFunction::GetElementValues`, such as when evaluating a `QuadratureFunctionCoefficient`. I believe it can be fixed by adding `ir->SetPointIndices();` to the bottom of `IntegrationRules::SegmentIntegrationRule`, although there may be a better or more idiomatic place to set the index values.

### PR DESCRIPTION
**Pull request by pazner**
Fixes #2333. Also makes `SetPointIndices` public. Every call to `IntegrationRule::SetSize` should be paired with a corresponding call to `SetPointIndices`.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2338](https://github.com/mfem/mfem/pull/2338) | @pazner | @tzanio | @v-dobrev + @tzanio | 06/17/21 | 06/18/21 | 06/25/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by v-dobrev — APPROVED** [review]

**Comment by v-dobrev** [comment]
LGTM

File: fem/intrules.cpp [hunk 1]
```diff
@@ -477,6 +476,7 @@ void QuadratureFunctions1D::GaussLobatto(const int np, IntegrationRule* ir)
    */
 
    ir->SetSize(np);
+   ir->SetPointIndices();
```
Comment (robert-chiodi) [inline fem/intrules.cpp:479]: This line needs to be added still for QuadratureFunctions1D::GaussLegendre

**Review by robert-chiodi — CHANGES_REQUESTED** [review]
Thanks for putting together this pull-request quickly to fix the issue. Just had two quick comments that will be quick to fix.

File: fem/intrules.hpp [hunk 2]
```diff
@@ -225,8 +222,14 @@ class IntegrationRule : public Array<IntegrationPoint>
       {
          (*this)[i].Init(i);
       }
+      SetPointIndices();
```
[the remark this answers is not in the document]
Comment (pazner) [reply fem/intrules.hpp]: You're right. Good catch.

File: fem/intrules.cpp (hunk 1 above)
Comment (pazner) [reply fem/intrules.cpp:480]: Thanks. It somehow fell between the cracks.

**Review by robert-chiodi — APPROVED** [review]
Looks great, thanks again!

**Comment by tzanio** [comment]
Merged in `next` for testing...
