### PR TITLE
Use physical values in QuadratureFunction::ProjectGridFunction

### LINKED ISSUE #4829: Projection of RT grid to quadrature functions does not work
When projecting an RT grid function onto a quadrature function, I am getting some mixed up data.
Specifically, adding this code to `ex5.cpp`:
```cpp
QuadratureSpace qspace(mesh, order_quad);
QuadratureFunction qf_u(qspace, dim);
qf_u.ProjectGridFunction(u);
```
produces with `./ex5 -m ../data/inline-quad.mesh`:
Image

While the naive implementation:
```cpp
QuadratureSpace qspace(mesh, order_quad);
QuadratureFunction qf_u(qspace, dim);

DenseMatrix values, tr;
for(int z = 0; z < mesh->GetNE(); z++)
{
  qf_u.GetValues(z, values);
  const IntegrationRule &ir = qf_u.GetIntRule(z);
  u.GetVectorValues(z, ir, values, tr);
}
```
gives the expected result:
Image

@v-dobrev , @pazner , is it a problem of #4669 or `QuadratureFunction::ProjectGridFunction()`?

### PR DESCRIPTION
**Pull request by pazner**
This ensures correct evaluation of H(div) grid functions.

Resolves #4829.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4830](https://github.com/mfem/mfem/pull/4830) | @pazner | @tzanio | @najlkin + @v-dobrev | 4/24/25 | 4/26/25 | 4/30/25 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

File: fem/quadinterpolator.hpp [hunk 1]
```diff
@@ -135,6 +135,10 @@ class QuadratureInterpolator
    /// Interpolate the values of the E-vector @a e_vec at quadrature points.
    void Values(const Vector &e_vec, Vector &q_val) const;
 
+   /// @brief Interpolate the physical values of the E-vector @a e_vec at
+   /// quadrature points.
+   void PhysicalValues(const Vector &e_vec, Vector &q_val) const;
```
Comment (najlkin) [inline fem/quadinterpolator.hpp:140]: For consistency with `PhysDerivatives()`, it would be better to use the name `PhysValues()` maybe 🤔 .

Comment (pazner) [reply fem/quadinterpolator.hpp]: For consistency I think you're right (though I personally prefer the unabbreviated version).

Changed in a5e62babfdab6301b4b48f4c24b63f0fd1f0fd75.

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by v-dobrev** [comment]
Here's the patch to support the case that fails in #4829, as explained here: https://github.com/mfem/mfem/issues/4829#issuecomment-2829478574:
```diff
diff --git a/fem/qinterp/eval_hdiv.hpp b/fem/qinterp/eval_hdiv.hpp
index aec9dc6c9d..8b5a750752 100644
--- a/fem/qinterp/eval_hdiv.hpp
+++ b/fem/qinterp/eval_hdiv.hpp
@@ -44,6 +44,7 @@ inline void EvalHDiv2D(const int NE,
 
    const int D1D = T_D1D ? T_D1D : d1d;
    const int Q1D = T_Q1D ? T_Q1D : q1d;
+   const int M1D = (Q1D > D1D) ? Q1D : D1D;
 
    const auto bo = Reshape(Bo_, Q1D, D1D-1);
    const auto bc = Reshape(Bc_, Q1D, D1D);
@@ -57,12 +58,13 @@ inline void EvalHDiv2D(const int NE,
              Reshape(y_, DIM, Q1D, Q1D, NE)) :
             Reshape(y_, Q1D, Q1D, 1, NE);
 
-   mfem::forall_3D(NE, Q1D, Q1D, DIM, [=] MFEM_HOST_DEVICE (int e)
+   mfem::forall_3D(NE, M1D, M1D, DIM, [=] MFEM_HOST_DEVICE (int e)
    {
       const int tidz = MFEM_THREAD_ID(z);
 
       const int D1D = T_D1D ? T_D1D : d1d;
       const int Q1D = T_Q1D ? T_Q1D : q1d;
+      const int M1D = (Q1D > D1D) ? Q1D : D1D;
 
       constexpr int MQ1 = T_Q1D ? T_Q1D : DofQuadLimits::HDIV_MAX_Q1D;
       constexpr int MD1 = T_D1D ? T_D1D : DofQuadLimits::HDIV_MAX_D1D;
@@ -85,13 +87,13 @@ inline void EvalHDiv2D(const int NE,
       {
          MFEM_FOREACH_THREAD(dy,y,D1D)
          {
-            MFEM_FOREACH_THREAD(qx,x,Q1D)
+            MFEM_FOREACH_THREAD(qx,x,M1D)
             {
                if (qx < D1D && dy < (D1D-1))
                {
                   X(qx + dy*D1D,vd) = x(qx+dy*D1D,vd,e);
                }
-               if (tidz == 0)
+               if (tidz == 0 && qx < Q1D)
                {
                   if (dy < (D1D-1)) { Bo(dy,qx) = bo(qx,dy); }
                   Bc(dy,qx) = bc(qx,dy);
```
Another option is to use `M1D x Q1D x DIM` for the thread block dimensions instead of `M1D x M1D x DIM`.

**Comment by pazner** [comment]
Thanks for the patch @v-dobrev! Committed in 24be7bca7bbfa2c67381533aecfdb9e03984ec3a. Are changes required also for the 3D case?

**Comment by v-dobrev** [comment]
> Thanks for the patch @v-dobrev! Committed in [24be7bc](https://github.com/mfem/mfem/commit/24be7bca7bbfa2c67381533aecfdb9e03984ec3a). Are changes required also for the 3D case?

The 3D case should be fine as it is -- I tested it (on CPU only) with the unit test (`test_quadinterpolator.cpp`) with the reduced quadrature rules from `ex5`. It may be good to double check it on GPU too but I think the code looks correct for that case.

**Review by v-dobrev — APPROVED** [review]

**Review by najlkin — APPROVED** [review]
I quickly tried `ex5.cpp` in 3D and looked fine on CPU.

**Comment by tzanio** [comment]
Merged in `next` for testing...
