### PR TITLE
Fix issue #2723

### LINKED ISSUE #2723: Report a few warnings
Compiler: g++ 9.3.0
MPI: mpich 3.3.2
OS: Ubuntu 20.04.3
CUDA: 11.5.1

In function ‘void mfem::SmemPAHcurlL2Apply3DTranspose(int, int, int, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

In function ‘void mfem::SmemPAHcurlL2Apply3D(int, int, int, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

In function ‘void mfem::SmemPACurlCurlApply3D(int, int, bool, int, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Array<double>&, const mfem::Vector&, const mfem::Vector&, mfem::Vector&) [with int MAX_D1D = 2; int MAX_Q1D = 3]’:
cc1plus: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 8 and 34359738368 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR resolves #2723 by introducing `MFEM_DEVICE_COMPILE` to guard code that is meant to only be executed on GPU.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2788](https://github.com/mfem/mfem/pull/2788) | @YohannDudouit | @v-dobrev | @v-dobrev + @tzanio + @dylan-copeland | 01/27/22 | 02/15/22 | 02/24/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
Thanks @YohannDudouit !

**Comment by YohannDudouit** [comment]
While testing this PR on Lassen, I see a lot of other warnings when using an old gcc, this PR does not address these warnings.

**Comment by tzanio** [comment]
Can you post some of these other warning?

**Comment by YohannDudouit** [comment]
When using gcc 4.9.3 (default compiler on Lassen), I see many of these warnings:
```
1500-029: (W) WARNING: subprogram mfem::PAHcurlApplyGradientTranspose2D(const int, const int, const int, const Array<double> &, const Array<double> &, const mfem::Vector &, mfem::Vector &)::(anonymous class)::operator()(int) could not be inlined into mfem::ForallWrap<1, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(int, int, int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, mfem::Vector &), &mfem::PAHcurlApplyGradientTranspose2D, 1>, const int, const int, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<3, double> >, (lambda at fem/bilininteg_hcurl.cpp:4850:3)>(const bool, const int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(int, int, int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, mfem::Vector &), &mfem::PAHcurlApplyGradientTranspose2D, 1>, const int, const int, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<3, double> > &&, (lambda at fem/bilininteg_hcurl.cpp:4850:3) &&, const int, const int, const int, const int)
```
It could be valuable to benchmark performance to see if this induces large performance differences.

**Comment by tzanio** [comment]
These go away with newer gcc, right?

**Review by v-dobrev — APPROVED** [review]
I did not test it (to make sure all warnings are gone) but this looks good to me.

**Comment by v-dobrev** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by v-dobrev** [comment]
> When using gcc 4.9.3 (default compiler on Lassen), I see many of these warnings:
> 
> ```
> 1500-029: (W) WARNING: subprogram mfem::PAHcurlApplyGradientTranspose2D(const int, const int, const int, const Array<double> &, const Array<double> &, const mfem::Vector &, mfem::Vector &)::(anonymous class)::operator()(int) could not be inlined into mfem::ForallWrap<1, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(int, int, int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, mfem::Vector &), &mfem::PAHcurlApplyGradientTranspose2D, 1>, const int, const int, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<3, double> >, (lambda at fem/bilininteg_hcurl.cpp:4850:3)>(const bool, const int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(int, int, int, const mfem::Array<double> &, const mfem::Array<double> &, const mfem::Vector &, mfem::Vector &), &mfem::PAHcurlApplyGradientTranspose2D, 1>, const int, const int, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<2, const double>, mfem::DeviceTensor<3, double> > &&, (lambda at fem/bilininteg_hcurl.cpp:4850:3) &&, const int, const int, const int, const int)
> ```
> 
> It could be valuable to benchmark performance to see if this induces large performance differences.

These warnings actually look like warnings from `nvcc` and I think they are not new.

**Review by tzanio — APPROVED** [review]

**Review by dylan-copeland — APPROVED** [review]
I verified that this fixes the warnings in the referenced issue.

**Comment by YohannDudouit** [comment]
> These go away with newer gcc, right?

Yes! I did not do extensive testing to see if other gcc versions suffer from these warnings.

**Comment by v-dobrev** [comment]
Merged in `next` for testing...

File: fem/bilininteg_hcurl.cpp [hunk 1]
```diff
@@ -1691,6 +1691,7 @@ static void SmemPACurlCurlApply3D(const int D1D,
                                   const Vector &x,
                                   Vector &y)
 {
+#ifdef MFEM_DEVICE_COMPILE
```
Comment (v-dobrev) [inline fem/bilininteg_hcurl.cpp:1694]: It turns out we botched this: the above `#ifdef` is always false in this function because it is a host function.

I guess we should moving the `#ifdef` inside the lambda.

Comment (YohannDudouit) [reply fem/bilininteg_hcurl.cpp:1694]: I'll do some compilation tests to understand better what is happening.

Comment (YohannDudouit) [reply fem/bilininteg_hcurl.cpp:1694]: I'm confused, if it is a CPU issue, why the CI did not catch it?

Comment (v-dobrev) [reply fem/bilininteg_hcurl.cpp:1694]: I think we don't run PA tests on CPU in CI.

**Comment by v-dobrev** [comment]
@YohannDudouit, @tzanio, @dylan-copeland, I updated this PR to fix the `Smem*` kernels warnings and some other warnings. Can you please take another look and test this if you can. I did test it myself in various settings and everything looks good.

**Comment by YohannDudouit** [comment]
I can't approve the PR, but I really like your solution, I think it's clean!

**Comment by tzanio** [comment]
This looks good to me too @v-dobrev, thanks for fixing it!

**Comment by v-dobrev** [comment]
Okay, I'll re-merge this in `next` for testing.

**Comment by v-dobrev** [comment]
Merged in `next` for testing...
